version: '2'
services:
  ngnix:
    image: nginx:1.11.10-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
  web:
    build: .
    encrypted_env_file: deployment.env.encrypted
    volumes:
      - .:/app
    links:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
    cached: true
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
  deploy:
    image: codeship/heroku-deployment
    encrypted_env_file: deployment.env.encrypted
    volumes:
      - ./:/deploy
